[project]
name = "easydel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.115.2",
    "fjformer==0.0.91",
    "flax>=0.10.2",
    "jax[tpu]>=0.5.0",
    "jinja2==3.1.5",
    "optax>=0.2.4",
    "prometheus-client==0.21.0",
    "termcolor>=2.5.0",
    "tqdm>=4.64.1",
    "transformers>=4.48.0",
    "uvicorn==0.32.0",
    "uvloop==0.21.0",
    "wandb==0.18.5",
]
