[project]
name = "easydel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi==0.115.2",
    "fjformer",
    "flax",
    "jax[tpu]",
    "jinja2==3.1.5",
    "optax",
    "prometheus-client==0.21.0",
    "termcolor>=2.5.0",
    "torch>=2.5.1",
    "torch-xla[tpu]>=2.5.1",
    "tqdm>=4.64.1",
    "transformers",
    "uvicorn==0.32.0",
    "uvloop==0.21.0",
    "wandb==0.18.5",
]
